version: "3.8"

services:
  pfdb:
    image: mariadb:latest
    container_name: "pathfinder-mariadb"
    environment:
      MARIADB_ROOT_PASSWORD: $MYSQL_PASSWORD
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    networks:
      pf:
        aliases:
          - "$MYSQL_HOST"
    volumes:
     - db_data:/var/lib/mysql
     - ./pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
    restart: always
  pf-redis:
    image: redis:6.2.13-alpine3.18
    command: ["redis-server", "--appendonly", "yes"]
    container_name: "pathfinder-redis"
    volumes:
      - redis_data:/data
    networks:
      pf:
        aliases:
          - "$REDIS_HOST"
    logging:
      driver: none
    restart: always
  pf-socket:
    image: ghcr.io/goryn-clade/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    container_name: "pathfinder-socket"
    networks:
      pf:
         aliases:
           - "$PATHFINDER_SOCKET_HOST"
    restart: always
  pf:
    container_name: "pathfinder"
    image: westtom/pathfinder:latest
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.pf.loadbalancer.server.port=80"
      - "traefik.http.routers.pf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pf.entrypoints=web"
      - "traefik.http.routers.pf-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pf-secure.entrypoints=websecure"
      - "traefik.http.routers.pf-secure.tls=true"
      - "traefik.http.routers.pf-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
      - "traefik.http.routers.pf.middlewares=redirecthttps"
    networks:
      - pf
      - web
    healthcheck:
      disable: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ./logs:/var/www/html/pathfinder/history/map
    depends_on:
      - pfdb
      - pf-redis
      - pf-socket
    restart: always
  traefik:
    image: "traefik:v3.0"
    container_name: "pathfinder-traefik"
    command:
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --entrypoints.websecure.http3.advertisedPort=443
      - --experimental.http3=true
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
    ports:
      - "80:80"
      - 443:443/tcp
      - 443:443/udp
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
    restart: always

volumes:
     data:
     db_data:
     redis_data:
networks:
    pf:
    web:
      external: true